# docker-compose.yml
services:
  api:
    build: .
    container_name: ai_analytics_api
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app:cached
    restart: unless-stopped

  dashboard:
    build: .
    container_name: ai_analytics_dashboard
    command: ["streamlit", "run", "dashboard.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app:cached
    restart: unless-stopped
